/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    projects: Project;
    pages: Page;
    redirects: Redirect;
    enquiries: Enquiry;
    faq: Faq;
    testimonials: Testimonial;
    credentials: Credential;
    careers: Career;
    founders: Founder;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    enquiries: EnquiriesSelect<false> | EnquiriesSelect<true>;
    faq: FaqSelect<false> | FaqSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    credentials: CredentialsSelect<false> | CredentialsSelect<true>;
    careers: CareersSelect<false> | CareersSelect<true>;
    founders: FoundersSelect<false> | FoundersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    navigation: Navigation;
    'site-settings': SiteSetting;
    seo: Seo;
    tracking: Tracking;
  };
  globalsSelect: {
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    seo: SeoSelect<false> | SeoSelect<true>;
    tracking: TrackingSelect<false> | TrackingSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  slug: string;
  /**
   * Controls display order — lower numbers show first.
   */
  order?: number | null;
  location?: string | null;
  year?: string | null;
  type?: string | null;
  scope?: string | null;
  services?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  cover?: (number | null) | Media;
  coverAspect?: ('landscape' | 'portrait' | 'wide') | null;
  hero: number | Media;
  images?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  description?: string | null;
  seo?: {
    /**
     * Falls back to the project title if left blank.
     */
    metaTitle?: string | null;
    /**
     * Falls back to the description above if left blank.
     */
    metaDescription?: string | null;
    /**
     * Falls back to the hero image if left blank.
     */
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * Route path, e.g. / or /services
   */
  path: string;
  status?: ('published' | 'draft') | null;
  seo?: {
    /**
     * Falls back to the page title above if left blank.
     */
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  /**
   * The page body, section by section. Add, remove and reorder blocks to change the page.
   */
  layout?:
    | (
        | {
            /**
             * Small uppercase label above the headline, e.g. "About Elpis".
             */
            label?: string | null;
            /**
             * One field per line break — controls how the large headline wraps.
             */
            headlineLines?:
              | {
                  line: string;
                  id?: string | null;
                }[]
              | null;
            body?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            image?: (number | null) | Media;
            /**
             * Local/static image path used until a real photo is uploaded via the Image field above, e.g. /images/studio/studio-atmosphere.jpg
             */
            fallbackImageUrl?: string | null;
            alt: string;
            aspectRatio?: ('21 / 9' | '16 / 9' | '4 / 3') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'imageBreak';
          }
        | {
            background?: ('warm-white' | 'soft-white' | 'navy') | null;
            /**
             * Small uppercase label above the headline. Optional.
             */
            label?: string | null;
            emphasis?: ('standard' | 'feature') | null;
            align?: ('left' | 'center') | null;
            /**
             * For "Feature" emphasis, separate lines with a | character.
             */
            headline?: string | null;
            /**
             * Optional second headline shown in the accent colour directly below the main headline (for "Feature" emphasis, separate lines with |).
             */
            headlineAccent?: string | null;
            /**
             * Separate paragraphs with a blank line.
             */
            body?: string | null;
            ctaLabel?: string | null;
            ctaHref?: string | null;
            /**
             * Optional — renders a small label/value grid below the body (e.g. Established, Team size).
             */
            stats?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            /**
             * Small print shown under the stats grid, e.g. noting the figures are placeholders.
             */
            statsDisclaimer?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textSection';
          }
        | {
            background?: ('warm-white' | 'soft-white' | 'navy') | null;
            label?: string | null;
            /**
             * One field per line break — controls how the large headline wraps.
             */
            headlineLines?:
              | {
                  line: string;
                  id?: string | null;
                }[]
              | null;
            /**
             * Shown instead of the grid when the Founders collection is empty.
             */
            note?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'founderGrid';
          }
        | {
            background?: ('warm-white' | 'soft-white' | 'navy') | null;
            label?: string | null;
            /**
             * One field per line break — controls how the large headline wraps.
             */
            headlineLines?:
              | {
                  line: string;
                  id?: string | null;
                }[]
              | null;
            /**
             * Shown instead of the grid when no credentials are published.
             */
            note?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'credentialsGrid';
          }
        | {
            background?: ('warm-white' | 'soft-white' | 'navy') | null;
            columns?:
              | {
                  label?: string | null;
                  headline: string;
                  body?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'splitText';
          }
        | {
            background?: ('warm-white' | 'soft-white' | 'navy') | null;
            label?: string | null;
            headline?: string | null;
            ctaLabel?: string | null;
            ctaHref?: string | null;
            columns?: ('1' | '2') | null;
            items?:
              | {
                  /**
                   * e.g. 01
                   */
                  number: string;
                  title: string;
                  body?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'numberedList';
          }
        | {
            label?: string | null;
            /**
             * One field per line break — controls how the large headline wraps.
             */
            headlineLines?:
              | {
                  line: string;
                  id?: string | null;
                }[]
              | null;
            body?: string | null;
            buttonLabel: string;
            buttonHref: string;
            /**
             * Adds a second button linking to the Site Settings WhatsApp number.
             */
            showWhatsappButton?: boolean | null;
            whatsappButtonLabel?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'ctaBanner';
          }
        | {
            items?:
              | {
                  /**
                   * e.g. 01
                   */
                  number: string;
                  title: string;
                  /**
                   * Optional larger sub-headline shown above the body (used by "why us" style reasons).
                   */
                  headline?: string | null;
                  body?: string | null;
                  /**
                   * e.g. "Client Provides" — leave blank if this item has no sub-list.
                   */
                  subListLabel?: string | null;
                  subList?:
                    | {
                        value: string;
                        id?: string | null;
                      }[]
                    | null;
                  /**
                   * e.g. "Outcome"
                   */
                  outcomeLabel?: string | null;
                  outcome?: string | null;
                  background?: ('warm-white' | 'soft-white' | 'navy') | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'stageList';
          }
        | {
            background?: ('warm-white' | 'soft-white' | 'navy') | null;
            label?: string | null;
            headline?: string | null;
            body?: string | null;
            items?:
              | {
                  number: string;
                  label: string;
                  href: string;
                  id?: string | null;
                }[]
              | null;
            ctaLabel?: string | null;
            ctaHref?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'linkList';
          }
        | {
            background?: ('warm-white' | 'soft-white' | 'navy') | null;
            imagePosition?: ('left' | 'right') | null;
            image?: (number | null) | Media;
            /**
             * Local/static image path used until a real photo is uploaded via the Image field above, e.g. /images/details/material-detail.jpg
             */
            fallbackImageUrl?: string | null;
            label?: string | null;
            headline: string;
            body?: string | null;
            /**
             * Optional short emphasised line, e.g. a key-benefit statement.
             */
            highlight?: string | null;
            /**
             * Optional — rendered as a compact list, e.g. "scope may include".
             */
            scopeItems?:
              | {
                  value: string;
                  id?: string | null;
                }[]
              | null;
            /**
             * Optional "best suited for" line.
             */
            suitedText?: string | null;
            ctaLabel?: string | null;
            ctaHref?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'imageText';
          }
        | {
            background?: ('warm-white' | 'soft-white' | 'navy') | null;
            label?: string | null;
            /**
             * One field per line break — controls how the large headline wraps.
             */
            headlineLines?:
              | {
                  line: string;
                  id?: string | null;
                }[]
              | null;
            note?: string | null;
            ctaLabel?: string | null;
            ctaHref?: string | null;
            /**
             * Optional — cap how many testimonials this block shows. Leave blank to show all published.
             */
            maxItems?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonialsGrid';
          }
        | {
            background?: ('warm-white' | 'soft-white' | 'navy') | null;
            label?: string | null;
            emptyStateBody?: string | null;
            emptyStateCtaLabel?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'careersList';
          }
        | {
            /**
             * How many of the most recent projects to feature.
             */
            count?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'featuredProjects';
          }
        | {
            text: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'marquee';
          }
        | {
            /**
             * Falls back to the site's default hero image if left blank.
             */
            image?: (number | null) | Media;
            imageAlt?: string | null;
            eyebrow?: string | null;
            /**
             * One field per line break — controls how the large headline wraps.
             */
            headlineLines?:
              | {
                  line: string;
                  id?: string | null;
                }[]
              | null;
            primaryCtaLabel?: string | null;
            primaryCtaHref?: string | null;
            secondaryCtaLabel?: string | null;
            secondaryCtaHref?: string | null;
            locationLine?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'homeHero';
          }
        | {
            background?: ('warm-white' | 'soft-white' | 'navy') | null;
            emptyStateBody?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faqAccordion';
          }
        | {
            label?: string | null;
            /**
             * One field per line break — controls how the large headline wraps.
             */
            headlineLines?:
              | {
                  line: string;
                  id?: string | null;
                }[]
              | null;
            body?: string | null;
            primaryCtaLabel?: string | null;
            primaryCtaHref?: string | null;
            secondaryCtaLabel?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contactDetails';
          }
        | {
            label?: string | null;
            /**
             * One field per line break — controls how the large headline wraps.
             */
            headlineLines?:
              | {
                  line: string;
                  id?: string | null;
                }[]
              | null;
            items?:
              | {
                  /**
                   * e.g. 01
                   */
                  number: string;
                  title: string;
                  body?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'stickyStepList';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * The old path to redirect from, e.g. /old-page
   */
  fromPath: string;
  /**
   * Where to send visitors, e.g. /services or a full https:// URL
   */
  toPath: string;
  type?: ('permanent' | 'temporary') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Submissions from the Start a Project assessment and the legacy contact form.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries".
 */
export interface Enquiry {
  id: number;
  status?: ('new' | 'contacted' | 'closed') | null;
  source?: ('start-a-project' | 'contact-form') | null;
  /**
   * Internal-only scoring signal — never shown to the visitor.
   */
  leadTier?: ('priority' | 'qualified' | 'review' | 'low-fit') | null;
  /**
   * Internal-only scoring signal — never shown to the visitor.
   */
  leadScore?: number | null;
  name: string;
  email: string;
  phone?: string | null;
  preferredContactMethod?: string | null;
  location?: string | null;
  projectType?: ('Interior Design' | 'Renovation' | 'Design & Build' | 'Not Sure Yet') | null;
  propertyType?: string | null;
  builtUpRange?: string | null;
  services?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  areas?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  transformationLevel?: string | null;
  budget?: string | null;
  timing?: string | null;
  details?: string | null;
  consent?: boolean | null;
  /**
   * Honeypot field — should always be blank. Not shown to real visitors.
   */
  company?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq".
 */
export interface Faq {
  id: number;
  question: string;
  answer: string;
  /**
   * Groups FAQs on the page, e.g. "Pricing", "Process", "Timeline". Leave blank for uncategorised.
   */
  category?: string | null;
  /**
   * Controls display order within its category — lower numbers show first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Client testimonials. Keep unpublished until a real client quote is on file — never fabricate a testimonial.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  /**
   * Only published testimonials appear on the site.
   */
  published?: boolean | null;
  /**
   * Controls display order — lower numbers show first.
   */
  order?: number | null;
  quote: string;
  authorName: string;
  /**
   * e.g. "Homeowner, Petaling Jaya"
   */
  authorDetail?: string | null;
  relatedProject?: (number | null) | Project;
  /**
   * Optional 1–5 star rating.
   */
  rating?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Licences, registrations, and certifications. Keep unpublished until the real credential is on file — never fabricate one.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "credentials".
 */
export interface Credential {
  id: number;
  /**
   * Only published credentials appear on the site.
   */
  published?: boolean | null;
  /**
   * Controls display order — lower numbers show first.
   */
  order?: number | null;
  /**
   * e.g. "SSM Registration", "CIDB Licence"
   */
  label: string;
  /**
   * e.g. a registration or licence number.
   */
  value?: string | null;
  issuer?: string | null;
  icon?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "careers".
 */
export interface Career {
  id: number;
  jobTitle: string;
  slug: string;
  status?: ('open' | 'closed') | null;
  /**
   * Controls display order — lower numbers show first.
   */
  order?: number | null;
  department?: string | null;
  location?: string | null;
  employmentType?: ('Full-time' | 'Part-time' | 'Internship' | 'Contract') | null;
  /**
   * Short one- or two-line summary shown in the job listing.
   */
  summary?: string | null;
  /**
   * Full responsibilities and requirements.
   */
  description?: string | null;
  /**
   * Overrides the site's default enquiry email for this listing, if set.
   */
  applyEmail?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Founder / principal profiles shown on the About page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "founders".
 */
export interface Founder {
  id: number;
  /**
   * Controls display order — lower numbers show first.
   */
  order?: number | null;
  name: string;
  /**
   * e.g. "CO-FOUNDER / PRINCIPAL DESIGNER"
   */
  title?: string | null;
  /**
   * 80–120 words: professional background, specialisation, design philosophy.
   */
  bio?: string | null;
  photo?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'enquiries';
        value: number | Enquiry;
      } | null)
    | ({
        relationTo: 'faq';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'credentials';
        value: number | Credential;
      } | null)
    | ({
        relationTo: 'careers';
        value: number | Career;
      } | null)
    | ({
        relationTo: 'founders';
        value: number | Founder;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  order?: T;
  location?: T;
  year?: T;
  type?: T;
  scope?: T;
  services?:
    | T
    | {
        value?: T;
        id?: T;
      };
  cover?: T;
  coverAspect?: T;
  hero?: T;
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  description?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  path?: T;
  status?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              label?: T;
              headlineLines?:
                | T
                | {
                    line?: T;
                    id?: T;
                  };
              body?: T;
              id?: T;
              blockName?: T;
            };
        imageBreak?:
          | T
          | {
              image?: T;
              fallbackImageUrl?: T;
              alt?: T;
              aspectRatio?: T;
              id?: T;
              blockName?: T;
            };
        textSection?:
          | T
          | {
              background?: T;
              label?: T;
              emphasis?: T;
              align?: T;
              headline?: T;
              headlineAccent?: T;
              body?: T;
              ctaLabel?: T;
              ctaHref?: T;
              stats?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              statsDisclaimer?: T;
              id?: T;
              blockName?: T;
            };
        founderGrid?:
          | T
          | {
              background?: T;
              label?: T;
              headlineLines?:
                | T
                | {
                    line?: T;
                    id?: T;
                  };
              note?: T;
              id?: T;
              blockName?: T;
            };
        credentialsGrid?:
          | T
          | {
              background?: T;
              label?: T;
              headlineLines?:
                | T
                | {
                    line?: T;
                    id?: T;
                  };
              note?: T;
              id?: T;
              blockName?: T;
            };
        splitText?:
          | T
          | {
              background?: T;
              columns?:
                | T
                | {
                    label?: T;
                    headline?: T;
                    body?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        numberedList?:
          | T
          | {
              background?: T;
              label?: T;
              headline?: T;
              ctaLabel?: T;
              ctaHref?: T;
              columns?: T;
              items?:
                | T
                | {
                    number?: T;
                    title?: T;
                    body?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        ctaBanner?:
          | T
          | {
              label?: T;
              headlineLines?:
                | T
                | {
                    line?: T;
                    id?: T;
                  };
              body?: T;
              buttonLabel?: T;
              buttonHref?: T;
              showWhatsappButton?: T;
              whatsappButtonLabel?: T;
              id?: T;
              blockName?: T;
            };
        stageList?:
          | T
          | {
              items?:
                | T
                | {
                    number?: T;
                    title?: T;
                    headline?: T;
                    body?: T;
                    subListLabel?: T;
                    subList?:
                      | T
                      | {
                          value?: T;
                          id?: T;
                        };
                    outcomeLabel?: T;
                    outcome?: T;
                    background?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        linkList?:
          | T
          | {
              background?: T;
              label?: T;
              headline?: T;
              body?: T;
              items?:
                | T
                | {
                    number?: T;
                    label?: T;
                    href?: T;
                    id?: T;
                  };
              ctaLabel?: T;
              ctaHref?: T;
              id?: T;
              blockName?: T;
            };
        imageText?:
          | T
          | {
              background?: T;
              imagePosition?: T;
              image?: T;
              fallbackImageUrl?: T;
              label?: T;
              headline?: T;
              body?: T;
              highlight?: T;
              scopeItems?:
                | T
                | {
                    value?: T;
                    id?: T;
                  };
              suitedText?: T;
              ctaLabel?: T;
              ctaHref?: T;
              id?: T;
              blockName?: T;
            };
        testimonialsGrid?:
          | T
          | {
              background?: T;
              label?: T;
              headlineLines?:
                | T
                | {
                    line?: T;
                    id?: T;
                  };
              note?: T;
              ctaLabel?: T;
              ctaHref?: T;
              maxItems?: T;
              id?: T;
              blockName?: T;
            };
        careersList?:
          | T
          | {
              background?: T;
              label?: T;
              emptyStateBody?: T;
              emptyStateCtaLabel?: T;
              id?: T;
              blockName?: T;
            };
        featuredProjects?:
          | T
          | {
              count?: T;
              id?: T;
              blockName?: T;
            };
        marquee?:
          | T
          | {
              text?: T;
              id?: T;
              blockName?: T;
            };
        homeHero?:
          | T
          | {
              image?: T;
              imageAlt?: T;
              eyebrow?: T;
              headlineLines?:
                | T
                | {
                    line?: T;
                    id?: T;
                  };
              primaryCtaLabel?: T;
              primaryCtaHref?: T;
              secondaryCtaLabel?: T;
              secondaryCtaHref?: T;
              locationLine?: T;
              id?: T;
              blockName?: T;
            };
        faqAccordion?:
          | T
          | {
              background?: T;
              emptyStateBody?: T;
              id?: T;
              blockName?: T;
            };
        contactDetails?:
          | T
          | {
              label?: T;
              headlineLines?:
                | T
                | {
                    line?: T;
                    id?: T;
                  };
              body?: T;
              primaryCtaLabel?: T;
              primaryCtaHref?: T;
              secondaryCtaLabel?: T;
              id?: T;
              blockName?: T;
            };
        stickyStepList?:
          | T
          | {
              label?: T;
              headlineLines?:
                | T
                | {
                    line?: T;
                    id?: T;
                  };
              items?:
                | T
                | {
                    number?: T;
                    title?: T;
                    body?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  fromPath?: T;
  toPath?: T;
  type?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries_select".
 */
export interface EnquiriesSelect<T extends boolean = true> {
  status?: T;
  source?: T;
  leadTier?: T;
  leadScore?: T;
  name?: T;
  email?: T;
  phone?: T;
  preferredContactMethod?: T;
  location?: T;
  projectType?: T;
  propertyType?: T;
  builtUpRange?: T;
  services?:
    | T
    | {
        value?: T;
        id?: T;
      };
  areas?:
    | T
    | {
        value?: T;
        id?: T;
      };
  transformationLevel?: T;
  budget?: T;
  timing?: T;
  details?: T;
  consent?: T;
  company?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq_select".
 */
export interface FaqSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  category?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  published?: T;
  order?: T;
  quote?: T;
  authorName?: T;
  authorDetail?: T;
  relatedProject?: T;
  rating?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "credentials_select".
 */
export interface CredentialsSelect<T extends boolean = true> {
  published?: T;
  order?: T;
  label?: T;
  value?: T;
  issuer?: T;
  icon?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "careers_select".
 */
export interface CareersSelect<T extends boolean = true> {
  jobTitle?: T;
  slug?: T;
  status?: T;
  order?: T;
  department?: T;
  location?: T;
  employmentType?: T;
  summary?: T;
  description?: T;
  applyEmail?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "founders_select".
 */
export interface FoundersSelect<T extends boolean = true> {
  order?: T;
  name?: T;
  title?: T;
  bio?: T;
  photo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  items?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Shown in the header wordmark and footer, unless a logo image is set below.
   */
  siteName?: string | null;
  /**
   * Optional. If set, replaces the text wordmark in the header.
   */
  logo?: (number | null) | Media;
  tagline?: string | null;
  /**
   * A curated set of font pairs. Self-hosted fonts must be built into the site ahead of time, so this isn't a free-text field.
   */
  fontPreset?: ('instrument-manrope' | 'playfair-inter' | 'playfair-montserrat') | null;
  /**
   * A curated set of color palettes. Elpis Editorial is the site's original dark-navy tone; Client Brand Palette applies the exact brand hex codes (#183A6B navy, #F7F3EA ivory, #1C1C1C charcoal, #C8A96A gold) site-wide.
   */
  colorPreset?: ('elpis-editorial' | 'client-palette') | null;
  contact?: {
    email?: string | null;
    whatsappUrl?: string | null;
    instagramUrl?: string | null;
    city?: string | null;
    country?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo".
 */
export interface Seo {
  id: number;
  defaultMetaTitle?: string | null;
  defaultMetaDescription?: string | null;
  defaultOgImage?: (number | null) | Media;
  /**
   * e.g. @elpisco (optional)
   */
  twitterHandle?: string | null;
  /**
   * Google Search Console verification code, if used.
   */
  googleSiteVerification?: string | null;
  /**
   * Uncheck to tell all search engines/crawlers not to index the site (e.g. while staging).
   */
  robotsIndex?: boolean | null;
  /**
   * Powers the Organization/LocalBusiness structured data (JSON-LD) that answer engines and AI crawlers (ChatGPT, Gemini, Perplexity, etc.) read to describe the business.
   */
  organization?: {
    /**
     * Falls back to Site Settings' site name if left blank.
     */
    legalName?: string | null;
    /**
     * Falls back to Site Settings' tagline if left blank.
     */
    description?: string | null;
    /**
     * e.g. $$ or $$$ (optional)
     */
    priceRange?: string | null;
    sameAs?:
      | {
          url: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Analytics and marketing tags. Leave a field blank to skip it entirely — nothing renders until an ID is set.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tracking".
 */
export interface Tracking {
  id: number;
  /**
   * e.g. GTM-XXXXXXX
   */
  gtmId?: string | null;
  /**
   * e.g. G-XXXXXXXXXX. Only needed if GA4 isn't already wired through GTM above.
   */
  ga4Id?: string | null;
  metaPixelId?: string | null;
  /**
   * Raw HTML/JS, e.g. a verification tag or a script snippet not covered above. Runs on every page. Use with caution.
   */
  customHeadCode?: string | null;
  /**
   * Raw HTML/JS, e.g. a chat widget embed. Runs on every page. Use with caution.
   */
  customBodyEndCode?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  items?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  logo?: T;
  tagline?: T;
  fontPreset?: T;
  colorPreset?: T;
  contact?:
    | T
    | {
        email?: T;
        whatsappUrl?: T;
        instagramUrl?: T;
        city?: T;
        country?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo_select".
 */
export interface SeoSelect<T extends boolean = true> {
  defaultMetaTitle?: T;
  defaultMetaDescription?: T;
  defaultOgImage?: T;
  twitterHandle?: T;
  googleSiteVerification?: T;
  robotsIndex?: T;
  organization?:
    | T
    | {
        legalName?: T;
        description?: T;
        priceRange?: T;
        sameAs?:
          | T
          | {
              url?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tracking_select".
 */
export interface TrackingSelect<T extends boolean = true> {
  gtmId?: T;
  ga4Id?: T;
  metaPixelId?: T;
  customHeadCode?: T;
  customBodyEndCode?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}