/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    projects: Project;
    pages: Page;
    redirects: Redirect;
    enquiries: Enquiry;
    faq: Faq;
    testimonials: Testimonial;
    credentials: Credential;
    careers: Career;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    enquiries: EnquiriesSelect<false> | EnquiriesSelect<true>;
    faq: FaqSelect<false> | FaqSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    credentials: CredentialsSelect<false> | CredentialsSelect<true>;
    careers: CareersSelect<false> | CareersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    navigation: Navigation;
    'site-settings': SiteSetting;
    seo: Seo;
    tracking: Tracking;
  };
  globalsSelect: {
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    seo: SeoSelect<false> | SeoSelect<true>;
    tracking: TrackingSelect<false> | TrackingSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  slug: string;
  /**
   * Controls display order — lower numbers show first.
   */
  order?: number | null;
  location?: string | null;
  year?: string | null;
  type?: string | null;
  scope?: string | null;
  services?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  cover?: (number | null) | Media;
  coverAspect?: ('landscape' | 'portrait' | 'wide') | null;
  hero: number | Media;
  images?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  description?: string | null;
  seo?: {
    /**
     * Falls back to the project title if left blank.
     */
    metaTitle?: string | null;
    /**
     * Falls back to the description above if left blank.
     */
    metaDescription?: string | null;
    /**
     * Falls back to the hero image if left blank.
     */
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * Route path, e.g. / or /services
   */
  path: string;
  status?: ('published' | 'draft') | null;
  seo?: {
    /**
     * Falls back to the page title above if left blank.
     */
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * The old path to redirect from, e.g. /old-page
   */
  fromPath: string;
  /**
   * Where to send visitors, e.g. /services or a full https:// URL
   */
  toPath: string;
  type?: ('permanent' | 'temporary') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Submissions from the site's contact form.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries".
 */
export interface Enquiry {
  id: number;
  status?: ('new' | 'contacted' | 'closed') | null;
  name: string;
  email: string;
  phone?: string | null;
  location?: string | null;
  projectType?: ('Interior Design' | 'Renovation' | 'Design & Build' | 'Not Sure Yet') | null;
  propertyType?: string | null;
  budget?: string | null;
  timing?: string | null;
  details?: string | null;
  /**
   * Honeypot field — should always be blank. Not shown to real visitors.
   */
  company?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq".
 */
export interface Faq {
  id: number;
  question: string;
  answer: string;
  /**
   * Groups FAQs on the page, e.g. "Pricing", "Process", "Timeline". Leave blank for uncategorised.
   */
  category?: string | null;
  /**
   * Controls display order within its category — lower numbers show first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Client testimonials. Keep unpublished until a real client quote is on file — never fabricate a testimonial.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  /**
   * Only published testimonials appear on the site.
   */
  published?: boolean | null;
  /**
   * Controls display order — lower numbers show first.
   */
  order?: number | null;
  quote: string;
  authorName: string;
  /**
   * e.g. "Homeowner, Petaling Jaya"
   */
  authorDetail?: string | null;
  relatedProject?: (number | null) | Project;
  /**
   * Optional 1–5 star rating.
   */
  rating?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Licences, registrations, and certifications. Keep unpublished until the real credential is on file — never fabricate one.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "credentials".
 */
export interface Credential {
  id: number;
  /**
   * Only published credentials appear on the site.
   */
  published?: boolean | null;
  /**
   * Controls display order — lower numbers show first.
   */
  order?: number | null;
  /**
   * e.g. "SSM Registration", "CIDB Licence"
   */
  label: string;
  /**
   * e.g. a registration or licence number.
   */
  value?: string | null;
  issuer?: string | null;
  icon?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "careers".
 */
export interface Career {
  id: number;
  jobTitle: string;
  slug: string;
  status?: ('open' | 'closed') | null;
  /**
   * Controls display order — lower numbers show first.
   */
  order?: number | null;
  department?: string | null;
  location?: string | null;
  employmentType?: ('Full-time' | 'Part-time' | 'Internship' | 'Contract') | null;
  /**
   * Short one- or two-line summary shown in the job listing.
   */
  summary?: string | null;
  /**
   * Full responsibilities and requirements.
   */
  description?: string | null;
  /**
   * Overrides the site's default enquiry email for this listing, if set.
   */
  applyEmail?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'enquiries';
        value: number | Enquiry;
      } | null)
    | ({
        relationTo: 'faq';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'credentials';
        value: number | Credential;
      } | null)
    | ({
        relationTo: 'careers';
        value: number | Career;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  order?: T;
  location?: T;
  year?: T;
  type?: T;
  scope?: T;
  services?:
    | T
    | {
        value?: T;
        id?: T;
      };
  cover?: T;
  coverAspect?: T;
  hero?: T;
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  description?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  path?: T;
  status?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  fromPath?: T;
  toPath?: T;
  type?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries_select".
 */
export interface EnquiriesSelect<T extends boolean = true> {
  status?: T;
  name?: T;
  email?: T;
  phone?: T;
  location?: T;
  projectType?: T;
  propertyType?: T;
  budget?: T;
  timing?: T;
  details?: T;
  company?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq_select".
 */
export interface FaqSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  category?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  published?: T;
  order?: T;
  quote?: T;
  authorName?: T;
  authorDetail?: T;
  relatedProject?: T;
  rating?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "credentials_select".
 */
export interface CredentialsSelect<T extends boolean = true> {
  published?: T;
  order?: T;
  label?: T;
  value?: T;
  issuer?: T;
  icon?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "careers_select".
 */
export interface CareersSelect<T extends boolean = true> {
  jobTitle?: T;
  slug?: T;
  status?: T;
  order?: T;
  department?: T;
  location?: T;
  employmentType?: T;
  summary?: T;
  description?: T;
  applyEmail?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  items?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Shown in the header wordmark and footer, unless a logo image is set below.
   */
  siteName?: string | null;
  /**
   * Optional. If set, replaces the text wordmark in the header.
   */
  logo?: (number | null) | Media;
  tagline?: string | null;
  /**
   * A curated set of font pairs. Self-hosted fonts must be built into the site ahead of time, so this isn't a free-text field.
   */
  fontPreset?: ('instrument-manrope' | 'playfair-inter') | null;
  contact?: {
    email?: string | null;
    whatsappUrl?: string | null;
    instagramUrl?: string | null;
    city?: string | null;
    country?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo".
 */
export interface Seo {
  id: number;
  defaultMetaTitle?: string | null;
  defaultMetaDescription?: string | null;
  defaultOgImage?: (number | null) | Media;
  /**
   * e.g. @elpisco (optional)
   */
  twitterHandle?: string | null;
  /**
   * Google Search Console verification code, if used.
   */
  googleSiteVerification?: string | null;
  /**
   * Uncheck to tell all search engines/crawlers not to index the site (e.g. while staging).
   */
  robotsIndex?: boolean | null;
  /**
   * Powers the Organization/LocalBusiness structured data (JSON-LD) that answer engines and AI crawlers (ChatGPT, Gemini, Perplexity, etc.) read to describe the business.
   */
  organization?: {
    /**
     * Falls back to Site Settings' site name if left blank.
     */
    legalName?: string | null;
    /**
     * Falls back to Site Settings' tagline if left blank.
     */
    description?: string | null;
    /**
     * e.g. $$ or $$$ (optional)
     */
    priceRange?: string | null;
    sameAs?:
      | {
          url: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Analytics and marketing tags. Leave a field blank to skip it entirely — nothing renders until an ID is set.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tracking".
 */
export interface Tracking {
  id: number;
  /**
   * e.g. GTM-XXXXXXX
   */
  gtmId?: string | null;
  /**
   * e.g. G-XXXXXXXXXX. Only needed if GA4 isn't already wired through GTM above.
   */
  ga4Id?: string | null;
  metaPixelId?: string | null;
  /**
   * Raw HTML/JS, e.g. a verification tag or a script snippet not covered above. Runs on every page. Use with caution.
   */
  customHeadCode?: string | null;
  /**
   * Raw HTML/JS, e.g. a chat widget embed. Runs on every page. Use with caution.
   */
  customBodyEndCode?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  items?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  logo?: T;
  tagline?: T;
  fontPreset?: T;
  contact?:
    | T
    | {
        email?: T;
        whatsappUrl?: T;
        instagramUrl?: T;
        city?: T;
        country?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo_select".
 */
export interface SeoSelect<T extends boolean = true> {
  defaultMetaTitle?: T;
  defaultMetaDescription?: T;
  defaultOgImage?: T;
  twitterHandle?: T;
  googleSiteVerification?: T;
  robotsIndex?: T;
  organization?:
    | T
    | {
        legalName?: T;
        description?: T;
        priceRange?: T;
        sameAs?:
          | T
          | {
              url?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tracking_select".
 */
export interface TrackingSelect<T extends boolean = true> {
  gtmId?: T;
  ga4Id?: T;
  metaPixelId?: T;
  customHeadCode?: T;
  customBodyEndCode?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}